services:
  postgres-db:
    image: postgres:15
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: sensi-news-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    networks:
      - app-network

  backend:
    build:
      context: ./backend/applications/system
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - postgres-db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-db:5432/sensi-news-db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    networks:
      - app-network

networks:
  app-network:
    driver: bridge