export enum EndpointConst {
  REGISTER = "/users/register",
  LOGIN = "/users/login",
  CURRENT_USER = "/users/current",
  TAGS = "/tags",
  TAGS_BY_IDS = "/tags/all",
  TAG_ID = "/tags/:id",
  ARTICLES_SEARCH = "/articles?withDeleted=false",
  ARTICLES_BY_TAGS = "/articles/search",
  ARTICLE_ID = "/articles/:id",
  ARTICLES = "/articles",
  ARTICLE_COMMENTS = "/articles/:id/comments",
  GENERATE = "/generate",
  COMMENTS = "/comments",
  COMMENTS_ID = "/comments/:id",
  ARTICLES_STATUS = "/articles/:id/status",
  ARTICLES_PENDING = "/articles/pending",
  COMMENTS_REPLY = "/comments/reply",
  ARTICLE_LIKE = "/articles/:id/like",
}
